### ISSUE TITLE
Find Symbol Patterns

### ISSUE THREAD

**Issue by Schildkroet** [Chadderz121/brainslug-wii#11]
Hello,
is there an example how to find symbol patterns? I don't understand how i can find them.
E.g. if i want to replace fprintf, how can i find these values: https://github.com/Chadderz121/brainslug-wii/blob/master/symbols/stdio.xml#L15-L19

**Comment by Leseratte10** [comment]
If you want to replace fprintf you don't need to do anything since the symbol pattern is already known :P

If you want to replace a function where the pattern isn't yet available in this repository, you'll need to find this function in one Wii game (maybe you can find one Wii game that has full symbols available), and then figure out an instruction sequence that's present in this function but not in any other function.

**Comment by Schildkroet** [comment]
No, i don't want to replace printf since it is already available (it was just an example)

> If you want to replace a function where the pattern isn't yet available in this repository, you'll need to find this function in one Wii game

Thats what i want to know. What is the workflow how to find a function. What tools do i need etc?

**Comment by Leseratte10** [comment]
Is the function you are looking for some generic function (like printf) that's probably present in lots of games? Or is it a game-specific function that's probably only available in one game?

If it's a generic function I'd grab the main ELF executable from one of these games: https://wiki.dolphin-emu.org/index.php?title=Ships_with_Debugging_Symbols and then open it up in a disassembler like ghidra. Then navigate to the function that you want to use (if you don't have an ELF with symbol names you'll have to find it yourself which will be difficult), and find an opcode sequence that seems unique to this function.

**Comment by Schildkroet** [comment]
Thx
